name: Update Spotify Recently Playing

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch:

jobs:
  update-spotify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Spotify Recently Playing
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        run: |
          curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=refresh_token&refresh_token=$SPOTIFY_REFRESH_TOKEN&client_id=$SPOTIFY_CLIENT_ID&client_secret=$SPOTIFY_CLIENT_SECRET" https://accounts.spotify.com/api/token > token.json
          ACCESS_TOKEN=$(jq -r .access_token token.json)
          curl -X GET "https://api.spotify.com/v1/me/player/recently-played" -H "Authorization: Bearer $ACCESS_TOKEN" > recently_played.json
          # Process the recently_played.json to update your GitHub page
